const express = require('express')
//const path = require('path');
const exclusiveGamesController = require('./controllers/exclusiveGames')
const notExclusiveGamesController = require('./controllers/notExclusiveGames')
const loginController = require('./controllers/loginController')
const eventDataController = require ('./controllers/dataEventController')
const router = express.Router()
//router.get('/',(request,response)=>response.status(200).sendFile(path.join(__dirname, './index.html')))
router.get('/games/:companyName',exclusiveGamesController.getAllGames)
router.get('/game/:companyName/:id',exclusiveGamesController.getGame)
router.post('/games', exclusiveGamesController.insertGame)
router.delete('/games',exclusiveGamesController.deleteGame)
router.put('/games',exclusiveGamesController.updateGame)
router.post('/gamesNotExclusive',notExclusiveGamesController.insertGame)
router.delete('/gamesNotExclusive',notExclusiveGamesController.deleteGame)
router.put('/gamesNotExclusive',notExclusiveGamesController.updateGame)
router.get('/login',loginController.getLogin)
router.post('/login',loginController.getLogin)
router.delete('/login/:id',loginController.deleteLogin)
router.put('/login',loginController.updateLogin)
router.get('/event/:idCompany',eventDataController.getEventData)
router.post('/event/:idCompany',eventDataController.insertEvent)
router.delete('/event/:id',eventDataController.deleteEvent)
router.put('/event/:id',eventDataController.updateEvent)
module.exports = router